services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: opena3xx.coordinator.rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: opena3xx
      RABBITMQ_DEFAULT_PASS: opena3xx
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - opena3xx-network

  seq:
    image: datalust/seq:2025.2
    container_name: opena3xx.coordinator.seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "admin123"
    ports:
      - "5341:5341"
      - "8080:80"
    volumes:
      - seq_data:/data
    networks:
      - opena3xx-network

volumes:
  webapi_data:
    driver: local
  rabbitmq_data:
    driver: local
  seq_data:
    driver: local

networks:
  opena3xx-network:
    driver: bridge
